baseurl = "https://jovial-curran-0c3e56.netlify.com/"
title = "Hacking Management"
languageCode = "en-us"
disqusShortname = "spf13"
copyright = "Copyright (c) 2008 - 2014, Steve Francia; all rights reserved."
MetaDataFormat = "yaml"

[author]
    name = "Steve Francia"

[indexes]
    tag = "tags"
    topic = "topics"

